### ISSUE TITLE
RSS feed plugin complains template content being used too early

### ISSUE THREAD

**Issue by ivaturi** [ivaturi/site#8]
This is happening:

```
[Browsersync] Serving files from: _site
[0] [11ty] File changed: vault/dfd-wtd.md
[0] [11ty] Unhandled rejection in promise: (more in DEBUG output)
[0] [11ty] > Tried to use templateContent too early (./vault/dfd-wtd.md)
[0] 
[0] `TemplateContentPrematureUseError` was thrown:
[0] [11ty]     TemplateContentPrematureUseError: Tried to use templateContent too early (./vault/dfd-wtd.md)
[0]         at Object.get templateContent [as templateContent] (/Users/abhi/Documents/vault/blog/node_modules/@11ty/eleventy/src/Template.js:697:23)
[0]         at Object.memberLookup (/Users/abhi/Documents/vault/blog/node_modules/nunjucks/src/runtime.js:251:17)
[0]         at eval (eval at _compile (/Users/abhi/Documents/vault/blog/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:62:59)
[0]         at iterCallback (/Users/abhi/Documents/vault/blog/node_modules/nunjucks/src/runtime.js:293:11)
[0]         at next (/Users/abhi/Documents/vault/blog/node_modules/nunjucks/src/lib.js:328:7)
[0]         at eval (eval at _compile (/Users/abhi/Documents/vault/blog/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:68:1)
[0]         at /Users/abhi/Documents/vault/blog/node_modules/@11ty/eleventy-plugin-rss/.eleventy.js:28:7
```

**Comment by ivaturi** [comment]
Removing the rss plugin for now, until I can figure out why it's not working.
